// SPDX-License-Identifier: Apache-2.0 OR EUPL-1.2
= jdtfmt
:toc: macro

*jdtfmt* is an opinionated Eclipse JDT-based Java source code formatter.

image:https://github.com/bmarwell/jdtfmt/actions/workflows/ci-backend.yml/badge.svg["jdtfmt",link=https://github.com/bmarwell/jdtfmt/actions/workflows/ci-backend.yml]
image:https://codecov.io/github/bmarwell/jdtfmt/graph/badge.svg?token=97T490QXQ2["codecov",link=https://codecov.io/github/bmarwell/jdtfmt]
image:https://img.shields.io/badge/License-Apache_2.0-blue.svg["License",link=https://opensource.org/licenses/Apache-2.0]
image:https://img.shields.io/badge/License-EUPL_1.2-blue["License EUPL",link=https://joinup.ec.europa.eu/software/page/eupl]

toc::[]

== Goals

* 🚫​⚙️ No config file by default
  ** ship a sane default config, similar to https://github.com/palantir/palantir-java-format[palantir-java-format].
* 🪞 idempotent operation
  ** do not do other/additional changes upon subsequent reformat operations
* 📝 reading and writing
  ** allows output on stdout or overwriting the input files
* 🚯 no AST loss
  ** do not swallow comments, intentional empty lines and line breaks, etc.
* 🚀 FAST
  ** The project aims to create a GraalVM-based binary for most architectures, so it can operate
     almost as fast as `gofmt` or similar tools.

== Implementation

* 💻 Uses PicoCLI for command line parsing
* 📝 Uses Eclipse JDT for formatting
* ⚙️ Uses GraalVM for creating native, statically linked stand-alone binaries

== FAQ

Why not call it `javafmt`?::
The JAVA® brand name is a registered trademark of Oracle, and except in limited circumstances, may not be used without a
written license from Oracle.
The “Java” name may be used in product, service, and event names without permission only in specific, limited ways.
+
… also, I wanted to keep the book open for the OpenJDK community to adopt an official tool with this name.

How opinionated is it?::
While there is a default rule, you can use other named rules or even foreign config files created by Eclipse IDE as well.
But I encourage everyone to use the default configuration – and let's discuss how well it is defined in the GitHub discussions and the issue tracker.

== Implementation status

Started.
The project is in an early stage and is not considered stable or feature-complete yet.

== Compiling

* Use Maven 4 or the Maven wrapper
* JDK 21 required

You can use `mvn verify` to create a tested and verified runnable application archive using jreleaser.
You can find and execute the archive in the path `cli/target/jreleaser/assemble/jdtfmt/java-archive`.
More info about these kinds of archives can be found in my blog post: https://blog.bmarwell.de/2025/04/12/creating-app-distribution-using-maven-jreleaser.html[Creating an App Distribution with Apache Maven and JReleaser].

Please note that Java 21 or better needs to be installed on your system and must be in the `PATH` environment variable.

=== Native Binaries

Why use native binaries?
Because they are fast, small, and do not require a JRE to be installed on the system.

Here is a simple comparison of this project running with both options:

[source,console]
----
❯ time ./cli/target/jdtfmt-1.0.0-SNAPSHOT .
Formatting file: ./cli/src/main/java/io/github/bmarwell/jdtfmt/nio/PathUtils.java
Formatting file: ./cli/src/main/java/io/github/bmarwell/jdtfmt/JdtFmt.java
Formatting file: ./cli/src/main/java/io/github/bmarwell/jdtfmt/value/FileProcessingResult.java
Formatting file: ./cli/src/main/java/io/github/bmarwell/jdtfmt/config/ConfigLoader.java
./cli/target/jdtfmt-1.0.0-SNAPSHOT .  0,01s user 0,02s system 95% cpu 0,034 total

❯ time ./cli/target/jreleaser/assemble/jdtfmt/java-archive/work/jdtfmt-1.0.0-SNAPSHOT/bin/jdtfmt .
Formatting file: ./cli/src/main/java/io/github/bmarwell/jdtfmt/nio/PathUtils.java
Formatting file: ./cli/src/main/java/io/github/bmarwell/jdtfmt/JdtFmt.java
Formatting file: ./cli/src/main/java/io/github/bmarwell/jdtfmt/value/FileProcessingResult.java
Formatting file: ./cli/src/main/java/io/github/bmarwell/jdtfmt/config/ConfigLoader.java
 .  2,01s user 0,13s system 232% cpu 0,923 total
----

As you can see, the native binary is about three times faster than the JAR distribution.

==== Compiling native binaries on linux

By default, a profile `dist-linux` is activated, which will create a native binary for Linux x86_64 using musl.
If you do not have musl and `libz.a` installed, you can use the profile `'-Pnative,!dist-linux'` to create a native binary using glibc instead.

== Further reading

* https://jqno.nl/post/2024/08/24/why-are-there-no-decent-code-formatters-for-java/[Why are there no decent code formatters for Java?] – by Jan Ouwens.
* link:++https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fformatter%2FDefaultCodeFormatterConstants.html++[Class DefaultCodeFormatterConstants] – the reference for the JDT code formatter config.
* https://github.com/diffplug/spotless/tree/main/plugin-maven#eclipse-jdt[Spotless Maven Plugin JDT setup] – the reference.

== License

This work is dual-licensed under Apache 2.0 and EUPL 1.2.
You may choose either license when using this work.

----
SPDX-License-Identifier: Apache-2.0 OR EUPL-1.2
----
