permissions:
  contents: read
name: Build Native

on:
  # must be triggered by build.yml
  workflow_call:
    inputs:
      head_sha:
        description: 'The commit SHA to checkout'
        required: false
        type: string

jobs:
  build-linux-x64:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
          ref: ${{ inputs.head_sha || github.sha }}

      - name: Set up JDK
        uses: actions/setup-java@v5.6.0
        with:
          java-version: 25
          distribution: 'graalvm'
          cache: maven

      - name: Install build dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential zlib1g-dev

      - name: Cache Maven packages
        id: restore-maven-package-cache
        uses: actions/cache/restore@v6.1.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build static native image for Linux
        run: |
          export PATH
          ./mvnw \
            --batch-mode \
            --show-version \
            --strict-checksums \
            --errors \
            --no-transfer-progress \
            -Pci,native,dist-linux \
            package

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: artifacts-linux-x64
          path: |
            cli/target/distributions/*.zip
            cli/target/distributions/*.tar.gz
            cli/target/jreleaser/assemble/jfmt/java-archive/*.zip
            cli/target/jreleaser/assemble/jfmt/java-archive/*.tar.gz

      - name: Save downloaded Maven packages
        uses: actions/cache/save@v6.1.0
        with:
          path: ~/.m2
          key: ${{ steps.restore-maven-package-cache.outputs.cache-primary-key }}
        if: github.event.workflow_run.event != 'pull_request'

  # 2nd part: build other platforms
  build-others:
    name: Build ${{ matrix.target }}
    needs: build-linux-x64
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: linux-aarch64
            os: ubuntu-22.04-arm
            arch: aarch64
          - target: macos-aarch64
            os: macos-14
            arch: aarch64
          - target: windows-x64
            os: windows-2022
            arch: x64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
          ref: ${{ inputs.head_sha || github.sha }}

      - name: Set up JDK
        uses: actions/setup-java@v5.6.0
        with:
          java-version: 25
          distribution: 'graalvm'
          cache: maven

      - name: Cache Maven packages
        id: restore-maven-package-cache
        uses: actions/cache/restore@v6.1.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build static native image for Linux
        run: |
          ./mvnw \
            --batch-mode \
            --show-version \
            --strict-checksums \
            --errors \
            --no-transfer-progress \
            -Pci,native,dist-linux \
            package
        if: startsWith(matrix.os, 'ubuntu-')

      - name: Build static native image for Windows / macOS
        shell: bash
        run: |
          ./mvnw \
            --batch-mode \
            --show-version \
            --strict-checksums \
            --errors \
            --no-transfer-progress \
            -Pci,native \
            package
        if: ${{ !startsWith(matrix.os, 'ubuntu-') }}

      - name: Save downloaded Maven packages
        uses: actions/cache/save@v6.1.0
        with:
          path: ~/.m2
          key: ${{ steps.restore-maven-package-cache.outputs.cache-primary-key }}
        if: github.event.workflow_run.event != 'pull_request'

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: artifacts-${{ matrix.os }}
          path: |
            cli/target/distributions/*.zip
            cli/target/distributions/*.tar.gz
